// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "magic-card": {
      name: "magic-card",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/magic-card.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/magic-card.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "flickering-grid": {
      name: "flickering-grid",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/flickering-grid.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/flickering-grid.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-hover-button": {
      name: "animated-hover-button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/animated-hover-button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/animated-hover-button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "rainbow-button": {
      name: "rainbow-button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/rainbow-button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/rainbow-button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "magic-card-demo": {
      name: "magic-card-demo",
      type: "registry:example",
      registryDependencies: ["magic-card"],
      files: ["src/registry/default/example/magic-card-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/magic-card-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "flickering-grid-demo": {
      name: "flickering-grid-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["src/registry/default/example/flickering-grid-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/flickering-grid-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "rainbow-button-demo": {
      name: "rainbow-button-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["src/registry/default/example/rainbow-button-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/rainbow-button-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-hover-button-demo": {
      name: "animated-hover-button-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["src/registry/default/example/animated-hover-button-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/animated-hover-button-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-1": {
      name: "button-1",
      type: "registry:example",
      registryDependencies: ["shadcn:button"],
      files: ["src/registry/default/example/button-1.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-2": {
      name: "button-2",
      type: "registry:example",
      registryDependencies: ["shadcn:button"],
      files: ["src/registry/default/example/button-2.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-2.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["src/registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
